# Generated by Django 3.2.4 on 2021-07-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=50)),
                ('re_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='usr_password',
        ),
    ]
