# Generated by Django 3.2.4 on 2021-07-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210701_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
