# Generated by Django 3.2.4 on 2021-07-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_createuser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='re_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
