# Generated by Django 3.2.4 on 2021-07-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210702_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateUser',
        ),
    ]
